---
- name: install tomcat6 packages
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - tomcat6

- name: ensure that tomcat listens on localhost only to alternative port
  lineinfile:
    dest: /etc/tomcat6/server.xml
    regexp: '^(\s*)<Connector(.*)port="(\d+)"(.*)$'
    backrefs: yes
    line: '\1<Connector address="127.0.0.1" port="{{ tomcat6_http_port }}"\4'
    state: present
  notify:
    - restart tomcat6

- name: ensure tomcat6 service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - tomcat6
